apiVersion: v1
kind: Service
metadata:
  name: airflow-svc
  namespace: airflow-executor
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - nodePort: 31725
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    name: airflow
  sessionAffinity: None



apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: airflow-k8sexecutor
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    name: airflow
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}