apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  namespace: airflow-example
subjects:
- kind: ServiceAccount
  name: airflow-sa
  namespace: airflow-executor
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io